version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/devmegablaster/jatt/cmd.JattVersion={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: jatt
    homepage: https://github.com/devmegablaster/jatt
    repository:
      owner: devmegablaster
      name: homebrew-devmegablaster
      branch: main
    commit_author:
      name: devmegablaster
      email: devmegablaster@gmail.com

nix:
  - name: jatt
    homepage: https://github.com/devmegablaster/jatt
    repository:
      owner: devmegablaster
      name: nur
      branch: master
    commit_author:
      name: devmegablaster
      email: devmegablaster@gmail.com

