// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ThemeChanger() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"theme-changer\" onClick=\"changeTheme()\"><div id=\"moon\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Svg("moon").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div id=\"sun\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Svg("sun").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><script>\n    function changeTheme() {\n        theme = localStorage.getItem(\"theme\");\n        if (theme == \"dark\") {\n          localStorage.setItem(\"theme\", \"light\");\n          document.documentElement.classList.remove(\"dark\");\n          document.getElementById(\"sun\").style.display = \"none\";\n          document.getElementById(\"moon\").style.display = \"block\";\n        } else {\n          localStorage.setItem(\"theme\", \"dark\");\n          document.documentElement.classList.add(\"dark\");\n          document.getElementById(\"moon\").style.display = \"none\";\n          document.getElementById(\"sun\").style.display = \"block\";\n        }\n      }\n\n      document.documentElement.classList.add(localStorage.getItem(\"theme\"));\n\n      if (localStorage.getItem(\"theme\") == \"dark\") {\n        document.getElementById(\"moon\").style.display = \"none\";\n        document.getElementById(\"sun\").style.display = \"block\";\n      } else {\n        document.getElementById(\"sun\").style.display = \"none\";\n        document.getElementById(\"moon\").style.display = \"block\";\n      }\n  </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
